name: Report

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.5"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - uses: fwal/setup-swift@v1.10.0
      with:
        swift-version: ${{ matrix.swift }}

    - uses: actions/cache@v2
      with:
        path: |
          ~/.build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        
    - run: swift test
      shell: bash

    - uses:  michaelhenry/create-report@v1.0.0
      with:
        report-title: "Sample report on ${{ matrix.os }} with Swift ${{ matrix.swft }}"
        report-summary: "# HELLO WORLD \n > This a sample code blockquote \n\n | Left columns  | Right columns |\n| ------------- |:-------------:|\n| left foo      | right foo     |\n| left bar      | right bar     |\n| left baz      | right baz     |"
